#########################################

# Editor por defecto
export EDITOR="vim"

# Enabling video acceleration
export LIBVA_DRIVER_NAME=vdpau
export VDPAU_DRIVER=r600

#Autocompletado usando tabulador
autoload -U compinit
compinit


autoload -U colors && colors

#Activa el uso de indicador avanzado
autoload -U promptinit
promptinit

#Mejora el autocompletado por defecto de zsh
zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'

#Configuración propia del indicador:
PROMPT="[%{$fg[yellow]%}%?%{$reset_color%}]%{$fg[red]%}%B%n%b #"
RPROMPT="<%{$fg[green]%}%~%{$reset_color%}>"

#Añade el soporte de historial
export HISTFILE=~/.zsh_history
export HISTSIZE=50000
export SAVEHIST=50000
setopt hist_ignore_all_dups
eval `dircolors -b`

#Funcionamiento de las teclas Inicio y Fin
case $TERM in
xterm)
bindkey '\eOH' beginning-of-line
bindkey '\eOF' end-of-line
bindkey '\e[2~' overwrite-mode
bindkey '\e[5~' beginning-of-buffer-or-history
bindkey '\e[6~' end-of-buffer-or-history
;;
aixterm)

#Uso de la tecla Supr
bindkey "\e[3~" delete-char # Del
bindkey "${key[Delete]}" delete-char

# similar commands but with aixterm sequences
;;
# and so on for other terminal types
esac

#Alias configurados
alias ls='ls --color=auto -F'
alias cp='gcp'
alias rm='mv --target-directory ~/.local/share/Trash/files'

#Key blindings de la wiki
bindkey "\e[1~" beginning-of-line # Home
bindkey "\e[4~" end-of-line # End
bindkey "\e[5~" beginning-of-history # PageUp
bindkey "\e[6~" end-of-history # PageDown
bindkey "\e[2~" quoted-insert # Ins
bindkey "\e[3~" delete-char # Del
bindkey "\e[5C" forward-word
bindkey "\eOc" emacs-forward-word
bindkey "\e[5D" backward-word
bindkey "\eOd" emacs-backward-word
bindkey "\e\e[C" forward-word
bindkey "\e\e[D" backward-word
bindkey "\e[Z" reverse-menu-complete # Shift+Tab
# for rxvt
bindkey "\e[7~" beginning-of-line # Home
bindkey "\e[8~" end-of-line # End
# for non RH/Debian xterm, can't hurt for RH/Debian xterm
bindkey "\eOH" beginning-of-line
bindkey "\eOF" end-of-line
